#!/bin/bash
#
# Commonly used functions

#######################################
# Detects yum or apt-get
# Globals:
#   None
# Arguments:
#   None
# Returns:
#   Package Manager command
#######################################
packagemanager() {
  declare -A OS_INFO;
  OS_INFO[/etc/redhat-release]=yum
  OS_INFO[/etc/debian_version]=apt-get

  for OS in ${!OS_INFO[@]}
  do 
    if [[ -f $OS ]]; then
      printf ${OS_INFO[$OS]}
    fi
  done
}

#######################################
# Report error to STDERR
# Globals:
#   None
# Arguments:
#   Error message
# Returns:
#   STDERR
#######################################
err() {
  printf "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $@\n" >&2
}

#######################################
# Formats stage announcements
# Globals:
#   None
# Arguments:
#   Stage announcement message
# Returns:
#   STDOUT
#######################################
announce() {
  printf "++++++++++++++++++++++++++++++++++++++\n"
  printf "\n"
  printf "$@\n"
  printf "\n"
  printf "++++++++++++++++++++++++++++++++++++++\n"
}

#######################################
# Run CyberArk Conjur CLI as admin user
# Globals:
#   CONJUR_ADMIN_PASSWORD
# Arguments:
#   CyberArk Conjur CLI Command
# Returns:
#   STDOUT
#######################################
run_conjur_cmd_as_admin() {
  local COMMAND=$(cat $@)

  conjur authn logout > /dev/null
  conjur authn login -u admin -p "$CONJUR_ADMIN_PASSWORD" > /dev/null

  local OUTPUT=$(eval "$COMMAND")

  conjur authn logout > /dev/null
  echo "$OUTPUT"
}

#######################################
# Load Conjur security policy
# Globals:
#   None
# Arguments:
#   Path to Conjur YAML policy file
# Returns:
#   STDOUT
#######################################
load_policy() {
  local POLICY_FILE=$1

  run_conjur_cmd_as_admin <<CMD
conjur policy load --as-group security_admin "policy/$POLICY_FILE"
CMD
}

#######################################
# Rotates the host's API Key for Conjur
# Globals:
#   None
# Arguments:
#   Host ID to rotate API key for
# Returns:
#   New API Key to STDOUT
#######################################
rotate_host_api_key() {
  local HOST=$1

  run_conjur_cmd_as_admin <<CMD
conjur host rotate_api_key -h $HOST
CMD
}