- hosts: localhost
  connection: local
  
  tasks:
  - name: Accept Weavescope Port 4040
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 4040
      protocol: TCP
      jump: ACCEPT
      
  - name: Accept Conjur Port 8080
    iptables:
      chain: INPUT
      source: 0.0.0.0/0
      ctstate: NEW,ESTABLISHED
      destination_port: 8080
      jump: ACCEPT